version: "3"

services:
  ApiGateway:
    image: nginx:alpine-slim
    container_name: BadeentenApiGateway
    restart: always
    volumes:
      - ./ApiGateway/html:/usr/share/nginx/html:ro
      - ./ApiGateway/conf/99-apigateway.conf:/etc/nginx/conf.d/99-apigateway.conf:ro
    ports:
      - "8000:80"

  MessageQueue:
    image: rabbitmq:3-management-alpine
    container_name: BadeentenMessageQueue
    restart: always
    volumes:
      - ./MessageQueue/data:/var/lib/rabbitmq
    ports:
      - "8001:15672"
      - "5672:5672"
