version: "3"

services:
  ApiGateway:
    image: nginx:alpine-slim
    container_name: BadeentenApiGateway
    restart: always
    volumes:
      - ../src/frontend:/usr/share/nginx/html:ro
      - ./ApiGateway/conf/99-apigateway.conf:/etc/nginx/conf.d/99-apigateway.conf:ro
    ports:
      - "7070:80"
  
  productservice:
    build:
      context: ../src/backend
      dockerfile: ./ProductService/Dockerfile
    volumes:
      - ./ProductService-data:/app/ProductService-data
    # only expose for debugging / development purposes
    # in production the service should not be accessible directly from the outside
    ports:
      - "8011:8080"

  orderservice:
    build:
      context: ../src/backend
      dockerfile: ./OrderService/Dockerfile
    volumes:
      - ./OrderService-data:/app/OrderService-data
    # only expose for debugging / development purposes
    # in production the service should not be accessible directly from the outside
    ports:
      - "8012:8080"
    
  Prometheus:
    image: prom/prometheus
    container_name: Prometheus
    restart: always
    volumes:
      - ./Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9190:9190"
