version: "3"

services:
  ApiGateway:
    image: nginx:alpine-slim
    container_name: BadeentenApiGateway
    restart: always
    volumes:
      - ../src/frontend:/usr/share/nginx/html:ro
      - ./ApiGateway/conf/99-apigateway.conf:/etc/nginx/conf.d/99-apigateway.conf:ro
    ports:
      - "7070:80"
  
  productservice:
    build:
      context: ../src/backend
      dockerfile: ./ProductService/Dockerfile
    volumes:
      - ./ProductService-data:/app/ProductService-data
    ports:
      - "8011:8080"

  orderservice:
    build:
      context: ../src/backend
      dockerfile: ./OrderService/Dockerfile
    volumes:
      - ./OrderService-data:/app/OrderService-data
    ports:
      - "8012:8080"
    
  Prometheus:
    image: prom/prometheus
    container_name: Prometheus
    restart: always
    volumes:
      - ./Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9190:9190"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ports:
      - "9201:9200" 
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - es-data:/usr/share/elasticsearch/data
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.2
    container_name: logstash
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5006:5000"
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9201
      - XPACK_SCREENSHOTTING_BROWSER_CHROMIUM_DISABLESANDBOX=true
    ports:
      - "5602:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk


networks:
  elk:
    driver: bridge

volumes:
  es-data:
    driver: local
