apiVersion: apps/v1
kind: Deployment
metadata:
  name: badeenten-api-gateway
  namespace: badeente
spec:
  replicas: 2
  selector:
    matchLabels:
      app: badeenten-api-gateway
  template:
    metadata:
      labels:
        app: badeenten-api-gateway
    spec:
      containers:
        - name: badeenten-api-gateway
          image: manuelgreub/BadeentenApiGateway:latest # Den Username mit deinem hier ersetzen
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 80 

---
# Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: badeenten-api-gateway-hpa
  namespace: badeente
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: badeenten-api-gateway
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50