apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: badeente
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      scrape_timeout: 10s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9190']

      - job_name: 'product-service'
        metrics_path: /metrics
        static_configs:
          - targets: ['productservice:8080']

      - job_name: 'order-service'
        metrics_path: /metrics
        static_configs:
          - targets: ['orderservice:8080']

      - job_name: 'api-gateway'
        metrics_path: /metrics
        static_configs:
          - targets: ['apigateway:80']